"""raw_articles: immutable capture of ingested items

Revision ID: a1c7e2b40f13
Revises: bf45495a0cae
Create Date: 2026-09-02 08:30:00.000000

Written by hand rather than autogenerated, and follows DATABASE.md's `raw_articles`
specification column for column.

Two indexes from that spec are deliberately NOT created here:

  * The HNSW index on `embedding`. DATABASE.md says to build it *after* the initial
    backfill -- building it on an empty table means rebuilding it later anyway, and
    HNSW construction on a populated table is far cheaper than incremental inserts
    into an index that started empty. It also cannot be built before the desktop has
    written any embeddings, which is Phase 3.

  * Nothing else. The GIN full-text index IS created, because search is wanted from
    the first ingested row and the table is small today.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "a1c7e2b40f13"
down_revision: str | None = "bf45495a0cae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "raw_articles",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("provider_id", sa.BigInteger(), nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "story_id",
            sa.BigInteger(),
            nullable=True,
            comment="No FK until `stories` exists in Phase 3; matches jobs.story_id.",
        ),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column(
            "url_hash",
            sa.LargeBinary(length=32),
            nullable=False,
            comment="sha256(canonical_url). The primary dedup guard, enforced by the "
            "database so two concurrent pollers cannot both insert.",
        ),
        sa.Column("original_url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("dek", sa.Text(), nullable=True),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("body_html_sanitized", sa.Text(), nullable=True),
        sa.Column("authors", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "discovered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column(
            "image_urls",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            comment="References only. Never rehosted, traced or recreated.",
        ),
        sa.Column(
            "raw_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Full provider response, so a normalization bug can be replayed "
            "against real input instead of refetched from an API that has moved on.",
        ),
        sa.Column("simhash", sa.BigInteger(), nullable=True),
        sa.Column("content_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column(
            "embedding",
            Vector(384),
            nullable=True,
            comment="Written by the desktop (ADR-0005). The VPS never computes this.",
        ),
        sa.Column("embedded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dedup_status", sa.String(length=16), nullable=False),
        sa.Column("duplicate_of_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "injection_flags",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Prompt-injection scan results (SECURITY.md 6). NOT NULL so "
            "'scanned and clean' is distinguishable from 'never scanned'.",
        ),
        sa.Column("ingest_status", sa.String(length=16), nullable=False),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["provider_id"], ["providers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["duplicate_of_id"], ["raw_articles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint("url_hash"),
    )

    # Every foreign key gets an index (CLAUDE.md).
    op.create_index("ix_raw_articles_provider_id", "raw_articles", ["provider_id"])
    op.create_index("ix_raw_articles_source_id", "raw_articles", ["source_id"])
    op.create_index("ix_raw_articles_duplicate_of_id", "raw_articles", ["duplicate_of_id"])

    op.create_index("ix_raw_articles_discovered_at", "raw_articles", [sa.text("discovered_at DESC")])
    op.create_index("ix_raw_articles_story_id", "raw_articles", ["story_id"])
    op.create_index("ix_raw_articles_ingest_status", "raw_articles", ["ingest_status"])

    # Partial: the dedup sweep scans only pending rows, and this becomes the largest
    # table in the database at 2-5k rows/day.
    op.create_index(
        "ix_raw_articles_dedup_pending",
        "raw_articles",
        ["dedup_status"],
        postgresql_where=sa.text("dedup_status = 'pending'"),
    )

    # SimHash candidates are looked up by 16-bit band, so the column needs its own index.
    op.create_index("ix_raw_articles_simhash", "raw_articles", ["simhash"])

    # Full-text over title + body. Expression index, so it cannot drift from the query.
    op.execute(
        "CREATE INDEX ix_raw_articles_fts ON raw_articles "
        "USING GIN (to_tsvector('english', title || ' ' || coalesce(body_text, '')))"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_raw_articles_fts")
    op.drop_index("ix_raw_articles_simhash", table_name="raw_articles")
    op.drop_index("ix_raw_articles_dedup_pending", table_name="raw_articles")
    op.drop_index("ix_raw_articles_ingest_status", table_name="raw_articles")
    op.drop_index("ix_raw_articles_story_id", table_name="raw_articles")
    op.drop_index("ix_raw_articles_discovered_at", table_name="raw_articles")
    op.drop_index("ix_raw_articles_duplicate_of_id", table_name="raw_articles")
    op.drop_index("ix_raw_articles_source_id", table_name="raw_articles")
    op.drop_index("ix_raw_articles_provider_id", table_name="raw_articles")
    op.drop_table("raw_articles")
