"""initial schema

Revision ID: bf45495a0cae
Revises: 0001_extensions
Create Date: 2026-08-31 00:15:49.023125

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "bf45495a0cae"
down_revision: str | None = "0001_extensions"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ad_placements",
        sa.Column("slot_key", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "min_height_px",
            sa.Integer(),
            nullable=False,
            comment="Space is reserved before load so ads cannot damage CLS.",
        ),
        sa.Column("categories", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("article_types", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("excluded_risk_tiers", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ad_placements")),
        sa.UniqueConstraint("slot_key", name=op.f("uq_ad_placements_slot_key")),
    )
    op.create_table(
        "affiliate_cta_templates",
        sa.Column("name", sa.String(length=96), nullable=False),
        sa.Column("button_text_template", sa.String(length=96), nullable=False),
        sa.Column("condition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("variant", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_affiliate_cta_templates")),
        sa.UniqueConstraint("name", name=op.f("uq_affiliate_cta_templates_name")),
    )
    op.create_table(
        "affiliate_disclosures",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("text_body", sa.Text(), nullable=False),
        sa.Column("placement_default", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_affiliate_disclosures")),
        sa.UniqueConstraint("slug", "version", name="uq_affiliate_disclosures_slug_ver"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index("ix_audit_logs_actor", "audit_logs", ["actor_type", "actor_id"], unique=False)
    op.create_index("ix_audit_logs_created_at", "audit_logs", ["created_at"], unique=False)
    op.create_index(
        "ix_audit_logs_entity", "audit_logs", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_request_id"), "audit_logs", ["request_id"], unique=False)
    op.create_table(
        "categories",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "is_commercial",
            sa.Boolean(),
            nullable=False,
            comment="Commercial sections are excluded from the Google News sitemap.",
        ),
        sa.Column("target_articles_per_day", sa.Integer(), nullable=True),
        sa.Column("seo_title", sa.String(length=255), nullable=True),
        sa.Column("seo_description", sa.Text(), nullable=True),
        sa.Column("accent_token", sa.String(length=64), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("slug", name=op.f("uq_categories_slug")),
    )
    op.create_index(op.f("ix_categories_parent_id"), "categories", ["parent_id"], unique=False)
    op.create_table(
        "newsletter_subscribers",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("confirm_token_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unsubscribed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("provider_ref", sa.String(length=128), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_newsletter_subscribers")),
        sa.UniqueConstraint("email", name=op.f("uq_newsletter_subscribers_email")),
    )
    op.create_index(
        op.f("ix_newsletter_subscribers_confirm_token_hash"),
        "newsletter_subscribers",
        ["confirm_token_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_newsletter_subscribers_public_id"),
        "newsletter_subscribers",
        ["public_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_newsletter_subscribers_status"), "newsletter_subscribers", ["status"], unique=False
    )
    op.create_table(
        "providers",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column(
            "adapter_class",
            sa.String(length=255),
            nullable=False,
            comment="Dotted path resolved at runtime.",
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("credential_ref", sa.String(length=128), nullable=True),
        sa.Column("rate_limit_per_hour", sa.Integer(), nullable=False),
        sa.Column("quota_used_today", sa.Integer(), nullable=False),
        sa.Column("poll_interval_minutes", sa.Integer(), nullable=False),
        sa.Column("default_reliability", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("circuit_state", sa.String(length=16), nullable=False),
        sa.Column("circuit_opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("cursor", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_providers")),
        sa.UniqueConstraint("slug", name=op.f("uq_providers_slug")),
    )
    op.create_table(
        "roles",
        sa.Column("slug", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("slug", name=op.f("uq_roles_slug")),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_protected", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
        sa.UniqueConstraint("key", name=op.f("uq_settings_key")),
    )
    op.create_table(
        "sources",
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("homepage_url", sa.Text(), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("source_type", sa.String(length=24), nullable=False),
        sa.Column("reliability_score", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column(
            "reliability_basis",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Inputs and last recomputation.",
        ),
        sa.Column(
            "bias_label",
            sa.String(length=32),
            nullable=True,
            comment="Recorded for balance reporting. NEVER used to suppress a source.",
        ),
        sa.Column(
            "is_primary_authority",
            sa.Boolean(),
            nullable=False,
            comment="True for .gov, courts, regulators and official organisation statements.",
        ),
        sa.Column("allow_auto_publish", sa.Boolean(), nullable=False),
        sa.Column("robots_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correction_count", sa.Integer(), nullable=False),
        sa.Column("contradiction_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("domain", name=op.f("uq_sources_domain")),
    )
    op.create_index("ix_sources_reliability", "sources", ["reliability_score"], unique=False)
    op.create_index(op.f("ix_sources_source_type"), "sources", ["source_type"], unique=False)
    op.create_table(
        "tags",
        sa.Column("slug", sa.String(length=96), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("is_trending", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("slug", name=op.f("uq_tags_slug")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False),
        sa.Column("mfa_secret_enc", sa.Text(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("session_epoch", sa.Integer(), nullable=False),
        sa.Column("subscription_tier", sa.String(length=16), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index(op.f("ix_users_public_id"), "users", ["public_id"], unique=True)
    op.create_table(
        "worker_nodes",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("previous_token_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("token_rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rotation_grace_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "capabilities",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment='e.g. {"gpu": true, "vram_gb": 12, "handlers": ["embed", "write"]}. The API only leases jobs a runner has advertised it can execute.',
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_job_count", sa.Integer(), nullable=False),
        sa.Column("gpu_name", sa.String(length=128), nullable=True),
        sa.Column("gpu_vram_free_mb", sa.Integer(), nullable=True),
        sa.Column("agent_version", sa.String(length=32), nullable=True),
        sa.Column("ip_last_seen", postgresql.INET(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_worker_nodes")),
        sa.UniqueConstraint("name", name=op.f("uq_worker_nodes_name")),
    )
    op.create_index(op.f("ix_worker_nodes_status"), "worker_nodes", ["status"], unique=False)
    op.create_index(
        op.f("ix_worker_nodes_token_hash"), "worker_nodes", ["token_hash"], unique=False
    )
    op.create_table(
        "articles",
        sa.Column("story_id", sa.BigInteger(), nullable=True),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=False),
        sa.Column("article_type", sa.String(length=32), nullable=False),
        sa.Column("headline", sa.String(length=300), nullable=False),
        sa.Column(
            "alternate_headlines",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Candidates with their per-axis scores.",
        ),
        sa.Column("dek", sa.Text(), nullable=False),
        sa.Column(
            "body_blocks",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Block list, so ad slots and CTAs are placed between blocks by rule and the renderer never needs dangerouslySetInnerHTML on model output.",
        ),
        sa.Column("body_markdown", sa.Text(), nullable=False),
        sa.Column("key_facts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("byline", sa.String(length=128), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("reading_time_seconds", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("editorial_confidence", sa.SmallInteger(), nullable=True),
        sa.Column("qa_report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("risk_tier", sa.String(length=16), nullable=False),
        sa.Column(
            "first_published_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Immutable once set. Drives the URL date path.",
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at_public", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seo_title", sa.String(length=255), nullable=False),
        sa.Column("meta_description", sa.Text(), nullable=False),
        sa.Column("og_title", sa.String(length=255), nullable=False),
        sa.Column("og_description", sa.Text(), nullable=False),
        sa.Column("structured_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("noindex", sa.Boolean(), nullable=False),
        sa.Column("hero_media_id", sa.BigInteger(), nullable=True),
        sa.Column("is_sponsored", sa.Boolean(), nullable=False),
        sa.Column("disclosure_text", sa.Text(), nullable=True),
        sa.Column("view_count", sa.BigInteger(), nullable=False),
        sa.Column("share_count", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "editorial_confidence IS NULL OR (editorial_confidence BETWEEN 0 AND 100)",
            name=op.f("ck_articles_editorial_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_articles_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hero_media_id"],
            ["media_assets.id"],
            name="fk_articles_hero_media_id_media_assets",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_articles")),
        sa.UniqueConstraint("category_id", "slug", name="uq_articles_category_slug"),
        sa.UniqueConstraint("id", "article_type", name="uq_articles_id_article_type"),
    )
    op.create_index(op.f("ix_articles_article_type"), "articles", ["article_type"], unique=False)
    op.create_index(op.f("ix_articles_category_id"), "articles", ["category_id"], unique=False)
    op.create_index(
        "ix_articles_category_published", "articles", ["category_id", "published_at"], unique=False
    )
    op.create_index(op.f("ix_articles_hero_media_id"), "articles", ["hero_media_id"], unique=False)
    op.create_index(
        "ix_articles_live",
        "articles",
        ["published_at"],
        unique=False,
        postgresql_where=sa.text("status = 'published'"),
    )
    op.create_index(op.f("ix_articles_public_id"), "articles", ["public_id"], unique=True)
    op.create_index(op.f("ix_articles_status"), "articles", ["status"], unique=False)
    op.create_index(
        "ix_articles_status_published_at", "articles", ["status", "published_at"], unique=False
    )
    op.create_index(op.f("ix_articles_story_id"), "articles", ["story_id"], unique=False)
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
    )
    op.create_index("ix_user_roles_role_id", "user_roles", ["role_id"], unique=False)
    op.create_table(
        "affiliate_articles",
        sa.Column(
            "article_id",
            sa.BigInteger(),
            nullable=True,
            comment="Null until the article row is generated.",
        ),
        sa.Column("article_type", sa.String(length=32), nullable=True),
        sa.Column("commercial_type", sa.String(length=40), nullable=False),
        sa.Column(
            "angle_rationale",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Why this format was chosen. The angle is derived from evidence, not guessed.",
        ),
        sa.Column("primary_keyword", sa.String(length=160), nullable=True),
        sa.Column("target_audience", sa.String(length=128), nullable=True),
        sa.Column(
            "ranking_criteria",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Required for any 'best' list. A ranking with no criteria fails QA.",
        ),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("publish_mode", sa.String(length=16), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disclosure_id", sa.BigInteger(), nullable=True),
        sa.Column("qa_report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "article_type NOT IN ('NEWS', 'ANALYSIS', 'OPINION', 'COMMENTARY')",
            name=op.f("ck_affiliate_articles_not_editorial_type"),
        ),
        sa.ForeignKeyConstraint(
            ["article_id", "article_type"],
            ["articles.id", "articles.article_type"],
            name="fk_affiliate_articles_article",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_affiliate_articles_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["disclosure_id"],
            ["affiliate_disclosures.id"],
            name=op.f("fk_affiliate_articles_disclosure_id_affiliate_disclosures"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_affiliate_articles")),
        sa.UniqueConstraint("article_id", name="uq_affiliate_articles_article_id"),
    )
    op.create_index(
        op.f("ix_affiliate_articles_public_id"), "affiliate_articles", ["public_id"], unique=True
    )
    op.create_index(
        "ix_affiliate_articles_status",
        "affiliate_articles",
        ["status", "scheduled_for"],
        unique=False,
    )
    op.create_table(
        "article_source_refs",
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=True),
        sa.Column("raw_article_id", sa.BigInteger(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("publisher", sa.String(length=255), nullable=False),
        sa.Column("ref_type", sa.String(length=24), nullable=False),
        sa.Column("accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_source_refs_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_article_source_refs_source_id_sources"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_article_source_refs")),
    )
    op.create_index(
        "ix_article_source_refs_article",
        "article_source_refs",
        ["article_id", "display_order"],
        unique=False,
    )
    op.create_index(
        op.f("ix_article_source_refs_raw_article_id"),
        "article_source_refs",
        ["raw_article_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_article_source_refs_source_id"), "article_source_refs", ["source_id"], unique=False
    )
    op.create_table(
        "article_tags",
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("tag_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_tags_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_article_tags_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("article_id", "tag_id", name=op.f("pk_article_tags")),
    )
    op.create_index("ix_article_tags_tag_id", "article_tags", ["tag_id"], unique=False)
    op.create_table(
        "article_versions",
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("headline", sa.String(length=300), nullable=False),
        sa.Column("body_markdown", sa.Text(), nullable=False),
        sa.Column("changed_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.Column("changed_by", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_versions_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_article_versions")),
        sa.UniqueConstraint("article_id", "version", name="uq_article_versions_article_version"),
    )
    op.create_index(
        op.f("ix_article_versions_article_id"), "article_versions", ["article_id"], unique=False
    )
    op.create_table(
        "corrections",
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("correction_type", sa.String(length=24), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("field_changed", sa.String(length=64), nullable=True),
        sa.Column("previous_value", sa.Text(), nullable=True),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("issued_by", sa.String(length=64), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_corrections_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corrections")),
    )
    op.create_index(op.f("ix_corrections_article_id"), "corrections", ["article_id"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("job_type", sa.String(length=64), nullable=False),
        sa.Column("priority", sa.SmallInteger(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("story_id", sa.BigInteger(), nullable=True),
        sa.Column("article_id", sa.BigInteger(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("leased_by_id", sa.BigInteger(), nullable=True),
        sa.Column("leased_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_jobs_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["leased_by_id"],
            ["worker_nodes.id"],
            name=op.f("fk_jobs_leased_by_id_worker_nodes"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_jobs_idempotency_key")),
    )
    op.create_index(op.f("ix_jobs_article_id"), "jobs", ["article_id"], unique=False)
    op.create_index(
        "ix_jobs_claimable",
        "jobs",
        ["priority", "available_at"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_index(op.f("ix_jobs_job_type"), "jobs", ["job_type"], unique=False)
    op.create_index(
        "ix_jobs_lease_expiry",
        "jobs",
        ["lease_expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'leased'"),
    )
    op.create_index(op.f("ix_jobs_public_id"), "jobs", ["public_id"], unique=True)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index("ix_jobs_status_created", "jobs", ["status", "created_at"], unique=False)
    op.create_index(op.f("ix_jobs_story_id"), "jobs", ["story_id"], unique=False)
    op.create_table(
        "media_assets",
        sa.Column("article_id", sa.BigInteger(), nullable=True),
        sa.Column("story_id", sa.BigInteger(), nullable=True),
        sa.Column("asset_role", sa.String(length=24), nullable=False),
        sa.Column(
            "storage_key",
            sa.Text(),
            nullable=False,
            comment="Path or object key -- never a fully-qualified URL.",
        ),
        sa.Column("mime_type", sa.String(length=64), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("bytes", sa.BigInteger(), nullable=False),
        sa.Column("blurhash", sa.String(length=64), nullable=True),
        sa.Column("alt_text", sa.Text(), nullable=False),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("credit", sa.Text(), nullable=True),
        sa.Column("rights_status", sa.String(length=24), nullable=False),
        sa.Column("license_ref", sa.Text(), nullable=True),
        sa.Column("attribution_required", sa.Boolean(), nullable=False),
        sa.Column("is_ai_generated", sa.Boolean(), nullable=False),
        sa.Column("ai_disclosure_text", sa.Text(), nullable=True),
        sa.Column("generator_model", sa.String(length=128), nullable=True),
        sa.Column("prompt_text", sa.Text(), nullable=True),
        sa.Column("negative_prompt", sa.Text(), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=True),
        sa.Column("generation_params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("safety_report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("usage_status", sa.String(length=16), nullable=False),
        sa.Column("cost", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column(
            "derivatives",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="AVIF/WebP/JPEG variants, generated on ingest.",
        ),
        sa.Column(
            "source_urls",
            postgresql.ARRAY(sa.Text()),
            nullable=True,
            comment="Reference only, for provenance. Third-party media is never rehosted.",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "width > 0 AND height > 0", name=op.f("ck_media_assets_positive_dimensions")
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_media_assets_article_id_articles"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
    )
    op.create_index(
        "ix_media_assets_article_role", "media_assets", ["article_id", "asset_role"], unique=False
    )
    op.create_index(op.f("ix_media_assets_public_id"), "media_assets", ["public_id"], unique=True)
    op.create_index(
        op.f("ix_media_assets_rights_status"), "media_assets", ["rights_status"], unique=False
    )
    op.create_index(op.f("ix_media_assets_story_id"), "media_assets", ["story_id"], unique=False)
    op.create_index(
        op.f("ix_media_assets_usage_status"), "media_assets", ["usage_status"], unique=False
    )
    op.create_table(
        "affiliate_merchants",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("network", sa.String(length=32), nullable=False),
        sa.Column("adapter_slug", sa.String(length=64), nullable=False),
        sa.Column("allows_page_fetch", sa.Boolean(), nullable=False),
        sa.Column(
            "image_rights",
            sa.String(length=24),
            nullable=False,
            comment="api_licensed | prohibited | unknown. Product photography is used only when the network's API supplies it with explicit usage rights.",
        ),
        sa.Column("logo_media_id", sa.BigInteger(), nullable=True),
        sa.Column("commission_notes", sa.Text(), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "credential_ref",
            sa.String(length=128),
            nullable=True,
            comment="Secret-store key name. Never the secret.",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["logo_media_id"],
            ["media_assets.id"],
            name=op.f("fk_affiliate_merchants_logo_media_id_media_assets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_affiliate_merchants")),
        sa.UniqueConstraint("slug", name=op.f("uq_affiliate_merchants_slug")),
    )
    op.create_index(
        op.f("ix_affiliate_merchants_domain"), "affiliate_merchants", ["domain"], unique=False
    )
    op.create_index(
        op.f("ix_affiliate_merchants_network"), "affiliate_merchants", ["network"], unique=False
    )
    op.create_table(
        "affiliate_campaigns",
        sa.Column("slug", sa.String(length=96), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("merchant_id", sa.BigInteger(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("clicks", sa.BigInteger(), nullable=False),
        sa.Column("conversions", sa.BigInteger(), nullable=False),
        sa.Column("revenue", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["affiliate_merchants.id"],
            name=op.f("fk_affiliate_campaigns_merchant_id_affiliate_merchants"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_affiliate_campaigns")),
        sa.UniqueConstraint("slug", name=op.f("uq_affiliate_campaigns_slug")),
    )
    op.create_index(
        op.f("ix_affiliate_campaigns_merchant_id"),
        "affiliate_campaigns",
        ["merchant_id"],
        unique=False,
    )
    op.create_table(
        "affiliate_products",
        sa.Column("merchant_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "product_ref",
            sa.String(length=128),
            nullable=False,
            comment="Merchant SKU / ASIN / catalogue id.",
        ),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("brand", sa.String(length=128), nullable=True),
        sa.Column("category_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "product_category",
            sa.String(length=255),
            nullable=True,
            comment="The merchant's own taxonomy string.",
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("specifications", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("price_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("price_currency", sa.String(length=3), nullable=True),
        sa.Column("price_source", sa.String(length=24), nullable=True),
        sa.Column("price_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rating_value", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("rating_count", sa.Integer(), nullable=True),
        sa.Column("rating_source", sa.String(length=24), nullable=True),
        sa.Column("availability", sa.String(length=32), nullable=True),
        sa.Column("availability_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("primary_image_media_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "missing_fields",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            comment="Drives the admin 'Needs Metadata' queue. Naming what is missing is what keeps the one-click workflow honest instead of guessing.",
        ),
        sa.Column("target_audience", sa.String(length=128), nullable=True),
        sa.Column("added_by_id", sa.BigInteger(), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "price_amount IS NULL OR price_source IS NOT NULL",
            name=op.f("ck_affiliate_products_price_requires_provenance"),
        ),
        sa.CheckConstraint(
            "rating_value IS NULL OR rating_source IS NOT NULL",
            name=op.f("ck_affiliate_products_rating_requires_provenance"),
        ),
        sa.ForeignKeyConstraint(
            ["added_by_id"],
            ["users.id"],
            name=op.f("fk_affiliate_products_added_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_affiliate_products_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["affiliate_merchants.id"],
            name=op.f("fk_affiliate_products_merchant_id_affiliate_merchants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["primary_image_media_id"],
            ["media_assets.id"],
            name=op.f("fk_affiliate_products_primary_image_media_id_media_assets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_affiliate_products")),
        sa.UniqueConstraint(
            "merchant_id", "product_ref", name="uq_affiliate_products_merchant_ref"
        ),
    )
    op.create_index(
        op.f("ix_affiliate_products_category_id"),
        "affiliate_products",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_affiliate_products_public_id"), "affiliate_products", ["public_id"], unique=True
    )
    op.create_index("ix_affiliate_products_status", "affiliate_products", ["status"], unique=False)
    op.create_table(
        "affiliate_article_products",
        sa.Column("affiliate_article_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("verdict_note", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["affiliate_article_id"],
            ["affiliate_articles.id"],
            name=op.f("fk_affiliate_article_products_affiliate_article_id_affiliate_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["affiliate_products.id"],
            name=op.f("fk_affiliate_article_products_product_id_affiliate_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_affiliate_article_products")),
        sa.UniqueConstraint(
            "affiliate_article_id", "product_id", name="uq_affiliate_article_products"
        ),
    )
    op.create_index(
        op.f("ix_affiliate_article_products_product_id"),
        "affiliate_article_products",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "affiliate_links",
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("campaign_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "original_url",
            sa.Text(),
            nullable=False,
            comment="Exactly as pasted. Tracking parameters preserved.",
        ),
        sa.Column("destination_url", sa.Text(), nullable=True),
        sa.Column("destination_domain", sa.String(length=255), nullable=True),
        sa.Column("network_tracking_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("clicks", sa.BigInteger(), nullable=False),
        sa.Column("impressions", sa.BigInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["affiliate_campaigns.id"],
            name=op.f("fk_affiliate_links_campaign_id_affiliate_campaigns"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["affiliate_products.id"],
            name=op.f("fk_affiliate_links_product_id_affiliate_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_affiliate_links")),
    )
    op.create_index(
        op.f("ix_affiliate_links_campaign_id"), "affiliate_links", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_affiliate_links_public_id"), "affiliate_links", ["public_id"], unique=True
    )
    op.create_index(
        "ix_affiliate_links_status", "affiliate_links", ["status", "last_checked_at"], unique=False
    )
    op.create_table(
        "affiliate_conversions",
        sa.Column("link_id", sa.BigInteger(), nullable=True),
        sa.Column("campaign_id", sa.BigInteger(), nullable=True),
        sa.Column("merchant_id", sa.BigInteger(), nullable=False),
        sa.Column("external_order_ref", sa.String(length=128), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("commission", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("import_source", sa.String(length=16), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["affiliate_campaigns.id"],
            name=op.f("fk_affiliate_conversions_campaign_id_affiliate_campaigns"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["link_id"],
            ["affiliate_links.id"],
            name=op.f("fk_affiliate_conversions_link_id_affiliate_links"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_affiliate_conversions")),
    )
    op.create_index(
        op.f("ix_affiliate_conversions_campaign_id"),
        "affiliate_conversions",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_affiliate_conversions_link_id"), "affiliate_conversions", ["link_id"], unique=False
    )
    op.create_index(
        op.f("ix_affiliate_conversions_merchant_id"),
        "affiliate_conversions",
        ["merchant_id"],
        unique=False,
    )
    op.create_table(
        "affiliate_ctas",
        sa.Column("affiliate_article_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("link_id", sa.BigInteger(), nullable=False),
        sa.Column("placement", sa.String(length=24), nullable=False),
        sa.Column("button_text", sa.String(length=96), nullable=False),
        sa.Column("button_variant", sa.String(length=32), nullable=False),
        sa.Column("disclosure_mode", sa.String(length=16), nullable=False),
        sa.Column(
            "is_visible",
            sa.Boolean(),
            nullable=False,
            comment="Set false automatically when the link is unhealthy.",
        ),
        sa.Column("impressions", sa.BigInteger(), nullable=False),
        sa.Column("clicks", sa.BigInteger(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["affiliate_article_id"],
            ["affiliate_articles.id"],
            name=op.f("fk_affiliate_ctas_affiliate_article_id_affiliate_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["link_id"],
            ["affiliate_links.id"],
            name=op.f("fk_affiliate_ctas_link_id_affiliate_links"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["affiliate_products.id"],
            name=op.f("fk_affiliate_ctas_product_id_affiliate_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_affiliate_ctas")),
    )
    op.create_index(
        "ix_affiliate_ctas_article",
        "affiliate_ctas",
        ["affiliate_article_id", "display_order"],
        unique=False,
    )
    op.create_index(op.f("ix_affiliate_ctas_link_id"), "affiliate_ctas", ["link_id"], unique=False)
    op.create_index(
        op.f("ix_affiliate_ctas_public_id"), "affiliate_ctas", ["public_id"], unique=True
    )
    op.create_table(
        "affiliate_link_health_checks",
        sa.Column("link_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("final_url", sa.Text(), nullable=True),
        sa.Column("redirect_count", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("result", sa.String(length=16), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["link_id"],
            ["affiliate_links.id"],
            name=op.f("fk_affiliate_link_health_checks_link_id_affiliate_links"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_affiliate_link_health_checks")),
    )
    op.create_index(
        "ix_affiliate_link_health_link_time",
        "affiliate_link_health_checks",
        ["link_id", "checked_at"],
        unique=False,
    )
    op.create_table(
        "affiliate_clicks",
        sa.Column("link_id", sa.BigInteger(), nullable=False),
        sa.Column("cta_id", sa.BigInteger(), nullable=True),
        sa.Column("article_id", sa.BigInteger(), nullable=True),
        sa.Column("campaign_id", sa.BigInteger(), nullable=True),
        sa.Column("merchant_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "clicked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("referrer_class", sa.String(length=16), nullable=False),
        sa.Column("device_class", sa.String(length=16), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("ip_truncated", postgresql.INET(), nullable=True),
        sa.Column("session_hash", sa.String(length=64), nullable=True),
        sa.Column("is_bot", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["cta_id"],
            ["affiliate_ctas.id"],
            name=op.f("fk_affiliate_clicks_cta_id_affiliate_ctas"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["link_id"],
            ["affiliate_links.id"],
            name=op.f("fk_affiliate_clicks_link_id_affiliate_links"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_affiliate_clicks")),
    )
    op.create_index(
        op.f("ix_affiliate_clicks_article_id"), "affiliate_clicks", ["article_id"], unique=False
    )
    op.create_index(
        op.f("ix_affiliate_clicks_campaign_id"), "affiliate_clicks", ["campaign_id"], unique=False
    )
    op.create_index(
        "ix_affiliate_clicks_link_time", "affiliate_clicks", ["link_id", "clicked_at"], unique=False
    )
    op.create_index(
        op.f("ix_affiliate_clicks_merchant_id"), "affiliate_clicks", ["merchant_id"], unique=False
    )
    op.create_index("ix_affiliate_clicks_time", "affiliate_clicks", ["clicked_at"], unique=False)
    # ### end Alembic commands ###

    # --- manual addition, do not remove on regeneration ---------------------
    # `articles.hero_media_id` -> `media_assets.id` closes a cycle with
    # `media_assets.article_id` -> `articles.id`. The model marks it use_alter=True so
    # Alembic can order the CREATE TABLEs, but `op.create_table` emits a bare
    # CreateTable and SQLAlchemy omits use_alter constraints from that DDL -- so the
    # constraint is silently skipped and never created. Verified: without this, the
    # only foreign key on `articles` is the category one.
    #
    # Adding it explicitly after both tables exist is the documented way to close a
    # circular reference.
    op.create_foreign_key(
        "fk_articles_hero_media_id_media_assets",
        "articles",
        "media_assets",
        ["hero_media_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    # Drop the deferred FK first: it is what makes the two tables mutually dependent,
    # so neither can be dropped while it stands.
    op.drop_constraint(
        "fk_articles_hero_media_id_media_assets", "articles", type_="foreignkey"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_affiliate_clicks_time", table_name="affiliate_clicks")
    op.drop_index(op.f("ix_affiliate_clicks_merchant_id"), table_name="affiliate_clicks")
    op.drop_index("ix_affiliate_clicks_link_time", table_name="affiliate_clicks")
    op.drop_index(op.f("ix_affiliate_clicks_campaign_id"), table_name="affiliate_clicks")
    op.drop_index(op.f("ix_affiliate_clicks_article_id"), table_name="affiliate_clicks")
    op.drop_table("affiliate_clicks")
    op.drop_index("ix_affiliate_link_health_link_time", table_name="affiliate_link_health_checks")
    op.drop_table("affiliate_link_health_checks")
    op.drop_index(op.f("ix_affiliate_ctas_public_id"), table_name="affiliate_ctas")
    op.drop_index(op.f("ix_affiliate_ctas_link_id"), table_name="affiliate_ctas")
    op.drop_index("ix_affiliate_ctas_article", table_name="affiliate_ctas")
    op.drop_table("affiliate_ctas")
    op.drop_index(op.f("ix_affiliate_conversions_merchant_id"), table_name="affiliate_conversions")
    op.drop_index(op.f("ix_affiliate_conversions_link_id"), table_name="affiliate_conversions")
    op.drop_index(op.f("ix_affiliate_conversions_campaign_id"), table_name="affiliate_conversions")
    op.drop_table("affiliate_conversions")
    op.drop_index("ix_affiliate_links_status", table_name="affiliate_links")
    op.drop_index(op.f("ix_affiliate_links_public_id"), table_name="affiliate_links")
    op.drop_index(op.f("ix_affiliate_links_campaign_id"), table_name="affiliate_links")
    op.drop_table("affiliate_links")
    op.drop_index(
        op.f("ix_affiliate_article_products_product_id"), table_name="affiliate_article_products"
    )
    op.drop_table("affiliate_article_products")
    op.drop_index("ix_affiliate_products_status", table_name="affiliate_products")
    op.drop_index(op.f("ix_affiliate_products_public_id"), table_name="affiliate_products")
    op.drop_index(op.f("ix_affiliate_products_category_id"), table_name="affiliate_products")
    op.drop_table("affiliate_products")
    op.drop_index(op.f("ix_affiliate_campaigns_merchant_id"), table_name="affiliate_campaigns")
    op.drop_table("affiliate_campaigns")
    op.drop_index(op.f("ix_affiliate_merchants_network"), table_name="affiliate_merchants")
    op.drop_index(op.f("ix_affiliate_merchants_domain"), table_name="affiliate_merchants")
    op.drop_table("affiliate_merchants")
    op.drop_index(op.f("ix_media_assets_usage_status"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_story_id"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_rights_status"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_public_id"), table_name="media_assets")
    op.drop_index("ix_media_assets_article_role", table_name="media_assets")
    op.drop_table("media_assets")
    op.drop_index(op.f("ix_jobs_story_id"), table_name="jobs")
    op.drop_index("ix_jobs_status_created", table_name="jobs")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_public_id"), table_name="jobs")
    op.drop_index(
        "ix_jobs_lease_expiry", table_name="jobs", postgresql_where=sa.text("status = 'leased'")
    )
    op.drop_index(op.f("ix_jobs_job_type"), table_name="jobs")
    op.drop_index(
        "ix_jobs_claimable", table_name="jobs", postgresql_where=sa.text("status = 'queued'")
    )
    op.drop_index(op.f("ix_jobs_article_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_corrections_article_id"), table_name="corrections")
    op.drop_table("corrections")
    op.drop_index(op.f("ix_article_versions_article_id"), table_name="article_versions")
    op.drop_table("article_versions")
    op.drop_index("ix_article_tags_tag_id", table_name="article_tags")
    op.drop_table("article_tags")
    op.drop_index(op.f("ix_article_source_refs_source_id"), table_name="article_source_refs")
    op.drop_index(op.f("ix_article_source_refs_raw_article_id"), table_name="article_source_refs")
    op.drop_index("ix_article_source_refs_article", table_name="article_source_refs")
    op.drop_table("article_source_refs")
    op.drop_index("ix_affiliate_articles_status", table_name="affiliate_articles")
    op.drop_index(op.f("ix_affiliate_articles_public_id"), table_name="affiliate_articles")
    op.drop_table("affiliate_articles")
    op.drop_index("ix_user_roles_role_id", table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_articles_story_id"), table_name="articles")
    op.drop_index("ix_articles_status_published_at", table_name="articles")
    op.drop_index(op.f("ix_articles_status"), table_name="articles")
    op.drop_index(op.f("ix_articles_public_id"), table_name="articles")
    op.drop_index(
        "ix_articles_live", table_name="articles", postgresql_where=sa.text("status = 'published'")
    )
    op.drop_index(op.f("ix_articles_hero_media_id"), table_name="articles")
    op.drop_index("ix_articles_category_published", table_name="articles")
    op.drop_index(op.f("ix_articles_category_id"), table_name="articles")
    op.drop_index(op.f("ix_articles_article_type"), table_name="articles")
    op.drop_table("articles")
    op.drop_index(op.f("ix_worker_nodes_token_hash"), table_name="worker_nodes")
    op.drop_index(op.f("ix_worker_nodes_status"), table_name="worker_nodes")
    op.drop_table("worker_nodes")
    op.drop_index(op.f("ix_users_public_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("tags")
    op.drop_index(op.f("ix_sources_source_type"), table_name="sources")
    op.drop_index("ix_sources_reliability", table_name="sources")
    op.drop_table("sources")
    op.drop_table("settings")
    op.drop_table("roles")
    op.drop_table("providers")
    op.drop_index(op.f("ix_newsletter_subscribers_status"), table_name="newsletter_subscribers")
    op.drop_index(op.f("ix_newsletter_subscribers_public_id"), table_name="newsletter_subscribers")
    op.drop_index(
        op.f("ix_newsletter_subscribers_confirm_token_hash"), table_name="newsletter_subscribers"
    )
    op.drop_table("newsletter_subscribers")
    op.drop_index(op.f("ix_categories_parent_id"), table_name="categories")
    op.drop_table("categories")
    op.drop_index(op.f("ix_audit_logs_request_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_entity", table_name="audit_logs")
    op.drop_index("ix_audit_logs_created_at", table_name="audit_logs")
    op.drop_index("ix_audit_logs_actor", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("affiliate_disclosures")
    op.drop_table("affiliate_cta_templates")
    op.drop_table("ad_placements")
    # ### end Alembic commands ###
